name: Yarn CI lib
on: [ pull_request ]
jobs:
  ciserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - run: yarn && yarn --cwd packages/lib build
      - run: yarn && yarn --cwd packages/lib test
